'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class activitylog
    Public Property id As Long
    Public Property timestamp As Nullable(Of Date)
    Public Property userid As Nullable(Of System.Guid)
    Public Property action As String

End Class
