'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class backteststat
    Public Property id As Integer
    Public Property index As String
    Public Property timestamp As Nullable(Of Date)
    Public Property begintimestamp As Nullable(Of Date)
    Public Property endtimestamp As Nullable(Of Date)
    Public Property symbol As String

End Class
