'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class backtest
    Public Property id As Integer
    Public Property month As String
    Public Property year As Nullable(Of Integer)
    Public Property marketdate As Nullable(Of Date)
    Public Property complete As Nullable(Of Boolean)

End Class
