'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class backtest
    Public Property id As Integer
    Public Property timestamp As Nullable(Of Date)
    Public Property index As String
    Public Property symbol As String
    Public Property buyprice As Nullable(Of Decimal)
    Public Property btomarketdate As Nullable(Of Date)
    Public Property open As Nullable(Of Boolean)
    Public Property stcmarketdate As Nullable(Of Date)
    Public Property sellprice As Nullable(Of Decimal)

End Class
