'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BlogComment
    Public Property Id As Integer
    Public Property BlogEntryId As Integer
    Public Property Title As String
    Public Property Name As String
    Public Property Email As String
    Public Property Url As String
    Public Property DatePublished As Date
    Public Property Text As String
    Public Property active As Boolean

End Class
