'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BlogEntry
    Public Property id As Integer
    Public Property DatePublished As Date
    Public Property Date_Modified As Date
    Public Property Author As String
    Public Property Name As String
    Public Property Title As String
    Public Property Description As String
    Public Property Text As String
    Public Property Active As Boolean

End Class
