'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HarvestPosition
    Public Property id As Integer
    Public Property symbol As String
    Public Property shares As Nullable(Of Integer)
    Public Property opendate As Nullable(Of Date)
    Public Property openprice As Nullable(Of Decimal)
    Public Property hedge As Nullable(Of Boolean)
    Public Property strike As Nullable(Of Decimal)
    Public Property closedate As Nullable(Of Date)
    Public Property closeprice As Nullable(Of Decimal)
    Public Property timestamp As Nullable(Of Date)
    Public Property open As Nullable(Of Boolean)
    Public Property openflag As String
    Public Property closeflag As String
    Public Property harvestkey As String
    Public Property hedgeid As Nullable(Of Integer)
    Public Property openrowid As Nullable(Of Integer)
    Public Property closerowid As Nullable(Of Integer)

End Class
