'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HarvestInterval
    Public Property ID As Integer
    Public Property [Date] As Date
    Public Property Interval As Integer
    Public Property OpenPrice As Decimal
    Public Property HighPrice As Decimal
    Public Property LowPrice As Decimal
    Public Property ClosePrice As Decimal
    Public Property Volume As Long
    Public Property symbol As String
    Public Property timestamp As Nullable(Of Date)

End Class
