'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HarvestIndex
    Public Property id As Integer
    Public Property harvestKey As String
    Public Property userID As Nullable(Of System.Guid)
    Public Property name As String
    Public Property product As String
    Public Property opentrigger As Nullable(Of Decimal)
    Public Property width As Nullable(Of Decimal)
    Public Property timestamp As Nullable(Of Date)
    Public Property active As Nullable(Of Boolean)
    Public Property shares As Nullable(Of Integer)
    Public Property hedge As Nullable(Of Boolean)
    Public Property hedgewidth As Nullable(Of Decimal)
    Public Property expdatewidth As Nullable(Of Integer)
    Public Property hedgelots As Nullable(Of Integer)
    Public Property pricetoprotect As Nullable(Of Decimal)
    Public Property OpeningMark As Nullable(Of Decimal)
    Public Property stocksectype As String
    Public Property optsectype As String
    Public Property currencytype As String
    Public Property exchange As String
    Public Property ordertype As String
    Public Property inforce As String
    Public Property opentimestamp As Nullable(Of Date)

End Class
