'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HarvestLog
    Public Property ID As Integer
    Public Property harvestkey As String
    Public Property marketdate As Nullable(Of Date)
    Public Property trans As Nullable(Of Long)
    Public Property opens As Nullable(Of Long)
    Public Property closes As Nullable(Of Long)
    Public Property closingmark As Nullable(Of Decimal)
    Public Property timestamp As Nullable(Of Date)
    Public Property otimestamp As Nullable(Of Date)
    Public Property hedgeprofit As Nullable(Of Decimal)
    Public Property stockprofit As Nullable(Of Decimal)
    Public Property currentcapital As Nullable(Of Decimal)
    Public Property maxcapital As Nullable(Of Decimal)
    Public Property sharesbought As Nullable(Of Integer)
    Public Property sharessold As Nullable(Of Integer)
    Public Property hedgebought As Nullable(Of Integer)
    Public Property hedgesold As Nullable(Of Integer)
    Public Property openingmark As Nullable(Of Decimal)

End Class
