'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HarvestMark
    Public Property id As Integer
    Public Property userid As Nullable(Of System.Guid)
    Public Property timestamp As Nullable(Of Date)
    Public Property symbol As String
    Public Property mark As Nullable(Of Decimal)
    Public Property turns As Nullable(Of Long)
    Public Property ctimestamp As Nullable(Of Date)
    Public Property open As Nullable(Of Boolean)
    Public Property harvestkey As String

End Class
