'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HarvestHedge
    Public Property id As Integer
    Public Property symbol As String
    Public Property type As String
    Public Property lots As Nullable(Of Integer)
    Public Property strike As Nullable(Of Decimal)
    Public Property exp As Nullable(Of Date)
    Public Property stockatopen As Nullable(Of Decimal)
    Public Property opendate As Nullable(Of Date)
    Public Property openprice As Nullable(Of Decimal)
    Public Property stockatclose As Nullable(Of Decimal)
    Public Property closedate As Nullable(Of Date)
    Public Property closeprice As Nullable(Of Decimal)
    Public Property open As Nullable(Of Boolean)
    Public Property timestamp As Nullable(Of Date)
    Public Property harvestkey As String
    Public Property positionID As Nullable(Of Integer)
    Public Property marketdate As Nullable(Of Date)
    Public Property targetexit As Nullable(Of Decimal)
    Public Property openrowid As Nullable(Of Integer)
    Public Property closerowid As Nullable(Of Integer)

End Class
