'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class harvestorder
    Public Property ID As Integer
    Public Property timestamp As Nullable(Of Date)
    Public Property harvestkey As String
    Public Property userid As Nullable(Of System.Guid)
    Public Property symbol As String
    Public Property btoorderdate As Nullable(Of Date)
    Public Property btoprice As Nullable(Of Decimal)
    Public Property btoopen As Nullable(Of Boolean)
    Public Property shares As Nullable(Of Integer)
    Public Property capital As Nullable(Of Decimal)
    Public Property btopermid As Nullable(Of Integer)
    Public Property btoorderid As Nullable(Of Integer)
    Public Property btoordertype As String
    Public Property btolimitprice As Nullable(Of Decimal)
    Public Property btoorderstatus As String
    Public Property quantity As Nullable(Of Integer)

End Class
