'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class myorder
    Public Property id As Integer
    Public Property timestamp As Nullable(Of Date)
    Public Property harvestkey As String
    Public Property btoStimestamp As Nullable(Of Date)
    Public Property btoSpermid As Nullable(Of Long)
    Public Property symbol As String
    Public Property shares As Nullable(Of Integer)
    Public Property btoSlimitprice As Nullable(Of Decimal)
    Public Property btoSorderstatus As String
    Public Property btoSfillprice As Nullable(Of Decimal)
    Public Property btoSCapital As Nullable(Of Decimal)
    Public Property lastactiontimestamp As Nullable(Of Date)
    Public Property btoSorderid As Nullable(Of Long)
    Public Property btoSfilledtimestamp As Nullable(Of Date)
    Public Property stcStimestamp As Nullable(Of Date)
    Public Property stcSpermid As Nullable(Of Long)
    Public Property stcSorderid As Nullable(Of Long)
    Public Property stcSlimitprice As Nullable(Of Decimal)
    Public Property stcSorderstatus As String
    Public Property stcSfillprice As Nullable(Of Decimal)
    Public Property stcSfilledtimestamp As Nullable(Of Date)
    Public Property LPbtoOpen As Nullable(Of Boolean)

End Class
