'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class onesigmawide
    Public Property recordId As Integer
    Public Property CreateDate As Date
    Public Property UpdateDate As Date
    Public Property EntryDate As Date
    Public Property Symbol As String
    Public Property Position As String
    Public Property StockPrice As Decimal
    Public Property IVPercentile As Decimal
    Public Property ExpirationDate As Date
    Public Property NumberLots As Integer
    Public Property ShortStrike As Decimal
    Public Property PITM As Decimal
    Public Property OpeningCredit As Decimal
    Public Property LongStrike As Decimal
    Public Property OpeningDebit As Decimal
    Public Property Status As String
    Public Property ClosingDebit As Decimal
    Public Property ClosingCredit As Decimal
    Public Property Account As String
    Public Property MaxProfitTarget As Decimal
    Public Property ExitDate As Nullable(Of Date)
    Public Property Notes As String

End Class
