'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Price
    Public Property id As Integer
    Public Property timestamp As Date
    Public Property dateandtime As Date
    Public Property interval As Integer
    Public Property symbol As String
    Public Property open As Decimal
    Public Property high As Decimal
    Public Property low As Decimal
    Public Property close As Decimal
    Public Property volume As Long
    Public Property [date] As Nullable(Of Date)

End Class
