'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pricing
    Public Property id As Integer
    Public Property symbolID As Integer
    Public Property openprice As Decimal
    Public Property highprice As Decimal
    Public Property lowprice As Decimal
    Public Property closeprice As Decimal
    Public Property adjcloseprice As Decimal
    Public Property volume As Long
    Public Property RangeDollars As Decimal
    Public Property RangePercent As Decimal
    Public Property Message As String
    Public Property marketdate As Date
    Public Property dateadded As Date
    Public Property changedollars As Nullable(Of Decimal)
    Public Property ChangePercent As Nullable(Of Decimal)
    Public Property GapDollars As Nullable(Of Decimal)
    Public Property GapPercent As Nullable(Of Decimal)
    Public Property AvgRange10Day As Nullable(Of Decimal)
    Public Property AvgRange50Day As Nullable(Of Decimal)
    Public Property AvgRange100Day As Nullable(Of Decimal)
    Public Property AvgRange300Day As Nullable(Of Decimal)
    Public Property AvgChange10Day As Nullable(Of Decimal)
    Public Property AvgChange50Day As Nullable(Of Decimal)
    Public Property AvgChange100Day As Nullable(Of Decimal)
    Public Property AvgChange300Day As Nullable(Of Decimal)
    Public Property RangePrctLast10 As Nullable(Of Decimal)
    Public Property RangePrctlast50 As Nullable(Of Decimal)
    Public Property RangePrctLast100 As Nullable(Of Decimal)
    Public Property RangePrctLast300 As Nullable(Of Decimal)
    Public Property ChangePrctLast10 As Nullable(Of Decimal)
    Public Property ChangePrctLast50 As Nullable(Of Decimal)
    Public Property ChangePrctLast100 As Nullable(Of Decimal)
    Public Property ChangePrctLast300 As Nullable(Of Decimal)
    Public Property StrikeWidth As Nullable(Of Decimal)
    Public Property StrikeToPrice As Nullable(Of Decimal)

End Class
