'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Profile
    Public Property UserId As System.Guid
    Public Property LastUpdatedDate As Date
    Public Property ScreenName As String
    Public Property image As String
    Public Property ProfileId As Integer
    Public Property mobile As String
    Public Property demo As Nullable(Of Boolean)
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Skype As String
    Public Property Location As String
    Public Property email As String
    Public Property MaxProfitPercent As Nullable(Of Short)
    Public Property ShowAny As Nullable(Of Boolean)
    Public Property ShowTrades As Nullable(Of Boolean)
    Public Property TOS As Nullable(Of Boolean)
    Public Property commission As Nullable(Of Decimal)

    Public Overridable Property User As User

End Class
