'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stockorder
    Public Property id As Integer
    Public Property timestamp As Nullable(Of Date)
    Public Property harvestkey As String
    Public Property symbol As String
    Public Property shares As Nullable(Of Integer)
    Public Property StockOpenOrderId As Nullable(Of Integer)
    Public Property StockOpenPermId As Nullable(Of Long)
    Public Property StockOpenLimitPrice As Nullable(Of Decimal)
    Public Property StockOpenFillPrice As Nullable(Of Decimal)
    Public Property StockOpenCapital As Nullable(Of Decimal)
    Public Property StockOpenFilled As Nullable(Of Boolean)
    Public Property StockOpenOrderStatus As String
    Public Property StockOpenFillTimeStamp As Nullable(Of Date)
    Public Property HedgePosition As Nullable(Of Boolean)

End Class
