'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stockorder
    Public Property id As Integer
    Public Property timestamp As Nullable(Of Date)
    Public Property OrderId As Nullable(Of Integer)
    Public Property PermID As Nullable(Of Integer)
    Public Property Symbol As String
    Public Property Action As String
    Public Property Status As String
    Public Property TickPrice As Nullable(Of Decimal)
    Public Property LimitPrice As Nullable(Of Decimal)
    Public Property Quantity As Nullable(Of Integer)
    Public Property OrderStatus As String
    Public Property OrderTimestamp As Nullable(Of Date)
    Public Property roboIndex As String
    Public Property matchID As String
    Public Property userid As Nullable(Of System.Guid)
    Public Property ordertype As String

End Class
