'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stockorder
    Public Property id As Integer
    Public Property timestamp As Nullable(Of Date)
    Public Property harvestkey As String
    Public Property symbol As String
    Public Property btoOrderId As Nullable(Of Integer)
    Public Property btoPermId As Nullable(Of Long)
    Public Property shares As Nullable(Of Integer)
    Public Property StockCapital As Nullable(Of Decimal)
    Public Property btoFilled As Nullable(Of Boolean)
    Public Property btofilltimestamp As Nullable(Of Date)
    Public Property btostockorderstatus As String
    Public Property btoStockLimitPrice As Nullable(Of Decimal)
    Public Property btoStockFillPrice As Nullable(Of Decimal)
    Public Property btohedgeorderid As Nullable(Of Integer)
    Public Property btohedgepermid As Nullable(Of Integer)
    Public Property hedgelots As Nullable(Of Integer)
    Public Property hedgestrike As Nullable(Of Decimal)
    Public Property hedgeExpiration As Nullable(Of Date)
    Public Property hedgeopen As Nullable(Of Boolean)

End Class
