'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Task
    Public Property taskID As Integer
    Public Property Task1 As String
    Public Property Status As String
    Public Property dateadded As Date
    Public Property dateupdated As Date
    Public Property datecompleted As Date

End Class
