'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ticket
    Public Property ticketID As Integer
    Public Property Type As String
    Public Property Priority As String
    Public Property Components As String
    Public Property Label As String
    Public Property Browsers As String
    Public Property Status As String
    Public Property FixVersions As String
    Public Property Assignee As String
    Public Property Reporter As String
    Public Property Description As String
    Public Property TicketPrefix As String
    Public Property dateadded As Date
    Public Property dateupdated As Date
    Public Property datecompleted As Date
    Public Property duedate As Date

    Public Overridable Property TicketComments As ICollection(Of TicketComment) = New HashSet(Of TicketComment)

End Class
