'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TradeLog
    Public Property tradeID As Long
    Public Property opentradeDATE As Date
    Public Property addDATE As Date
    Public Property openingTRADE As String
    Public Property closetradeDATE As Date
    Public Property closeDATE As Date
    Public Property closingTRADE As String
    Public Property expirationDATE As Date
    Public Property openingAMOUNT As Decimal
    Public Property closingAMOUNT As Decimal
    Public Property userID As String
    Public Property status As Nullable(Of Boolean)
    Public Property dit As Nullable(Of Integer)
    Public Property uniqueID As String

End Class
