'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TradeDetail
    Public Property tradeID As Long
    Public Property addDATE As Date
    Public Property transTYPE As String
    Public Property lots As Integer
    Public Property tradeTYPE As String
    Public Property symbol As String
    Public Property count As String
    Public Property expirationDATE As Date
    Public Property shortCALL As Decimal
    Public Property longCALL As Decimal
    Public Property shortPUT As Decimal
    Public Property longPUT As Decimal
    Public Property creditreceived As Decimal
    Public Property open As Boolean
    Public Property debitpaid As Decimal
    Public Property openDATE As Date
    Public Property closeDATE As Date
    Public Property uniqueid As String
    Public Property winFLAG As Nullable(Of Boolean)
    Public Property dit As Nullable(Of Long)
    Public Property updateDATE As Nullable(Of Date)
    Public Property userID As String
    Public Property exp As String

End Class
