'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_aspnet_Users
    Public Property ApplicationId As System.Guid
    Public Property UserId As System.Guid
    Public Property UserName As String
    Public Property LoweredUserName As String
    Public Property MobileAlias As String
    Public Property IsAnonymous As Boolean
    Public Property LastActivityDate As Date

End Class
