'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_avg_daily_gap
    Public Property Symbol As String
    Public Property Name As String
    Public Property Product As String
    Public Property ten_day_range As Nullable(Of Decimal)
    Public Property fifty_day_range As Nullable(Of Decimal)
    Public Property one_hundred_day_range As Nullable(Of Decimal)
    Public Property three_hundred_day_range As Nullable(Of Decimal)

End Class
