'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_aspnet_Applications
    Public Property ApplicationName As String
    Public Property LoweredApplicationName As String
    Public Property ApplicationId As System.Guid
    Public Property Description As String

End Class
