'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_aspnet_MembershipUsers
    Public Property UserId As System.Guid
    Public Property PasswordFormat As Integer
    Public Property MobilePIN As String
    Public Property Email As String
    Public Property LoweredEmail As String
    Public Property PasswordQuestion As String
    Public Property PasswordAnswer As String
    Public Property IsApproved As Boolean
    Public Property IsLockedOut As Boolean
    Public Property CreateDate As Date
    Public Property LastLoginDate As Date
    Public Property LastPasswordChangedDate As Date
    Public Property LastLockoutDate As Date
    Public Property FailedPasswordAttemptCount As Integer
    Public Property FailedPasswordAttemptWindowStart As Date
    Public Property FailedPasswordAnswerAttemptCount As Integer
    Public Property FailedPasswordAnswerAttemptWindowStart As Date
    Public Property Comment As String
    Public Property ApplicationId As System.Guid
    Public Property UserName As String
    Public Property MobileAlias As String
    Public Property IsAnonymous As Boolean
    Public Property LastActivityDate As Date

End Class
