'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_aspnet_WebPartState_Shared
    Public Property PathId As System.Guid
    Public Property DataSize As Nullable(Of Integer)
    Public Property LastUpdatedDate As Date

End Class
