'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_Pricings_DESC
    Public Property id As Integer
    Public Property symbolID As Integer
    Public Property openprice As Decimal
    Public Property highprice As Decimal
    Public Property lowprice As Decimal
    Public Property closeprice As Decimal
    Public Property adjcloseprice As Decimal
    Public Property volume As Long
    Public Property RangeDollars As Decimal
    Public Property RangePercent As Decimal
    Public Property Message As String
    Public Property marketdate As Date
    Public Property dateadded As Date

End Class
