'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Weekly
    Public Property id As Integer
    Public Property Symbol As String
    Public Property Name As String
    Public Property Product As String
    Public Property IssueDate As String
    Public Property firstissuedate As Date
    Public Property lastupdate As Date
    Public Property active As Boolean
    Public Property strikewidth As Nullable(Of Decimal)

End Class
