'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class wStockOrder
    Public Property id As Integer
    Public Property createdtimestamp As Nullable(Of Date)
    Public Property userid As Nullable(Of System.Guid)
    Public Property keyid As String
    Public Property orderid As Nullable(Of Integer)
    Public Property permid As Nullable(Of Integer)
    Public Property symbol As String
    Public Property orderopen As Nullable(Of Boolean)

End Class
